### PR TITLE
23 frequency table unit tests

### LINKED ISSUE #23: Frequency table unit tests
New unit tests needed now that outputs contain proportions rather than raw frequencies. 

Need new tests to check missing values are being handled correctly.

### LINKED ISSUE #25: Frequency Table QA
- [x] Change references to columns from last year’s dataset to this year's.
- [x] Fix incorrect capitalization.
- [ ] Carry out some sense checks and compare against the smartsurvey outputs.
- [x] Compare with last year’s figures to see if anything changed drastically, in which case there might be a mistake there somewhere. Things to look for would be counts of zero (very unlikely, usually a bug), numbers that look higher or lower than they should, percentages that should add up to 100%, but don’t, etc.

### PR DESCRIPTION
**Pull request by ldavies99**
Resolves #23
All unit tests have been updated to proportions rather than count.

Partially resolves #25
Corrected incorrect capitilisation and references to last year's columns.

### CODE REVIEW

**Comment by ldavies99** [comment]
I've realised that #24 already changes the summary tables to return proportions.

File: tests/testthat/test-summarise_coding_practices.R [hunk 1]
```diff
@@ -10,49 +11,48 @@ dummy_data <- data.frame(prac_use_open_source = c(rep("Never", 3), rep("Sometime
...
+                                  rep("I collect my code and supporting material into packages", 6),
+                                  rep("I follow a standard directory structure when programming", 6),
+                                  rep("I follow coding guidelines or style guides when programming", 6),
+                                  rep("I unit test my code", 6),
+                                  rep("I use a source code version control system e.g. Git", 6),
+                                  rep("I use open source software when programming", 6),
+                                  rep("I write code to automatically quality assure data", 6),
+                                  rep("I write repetitive elements in my code as functions", 6),
+                                  rep("My team applies the principles set out in the Aqua book when carrying out analysis as code", 6),
+                                  rep("My team open sources its code", 6)),
```
Comment (RuSnook) [inline tests/testthat/test-summarise_coding_practices.R:36]:
```suggestion
  expected <- data.frame(name = rep(c("Code my team writes is reviewed by a colleague", 
                                  "I collect my code and supporting material into packages", 
                                  "I follow a standard directory structure when programming", 
                                  "I follow coding guidelines or style guides when programming",
                                  "I unit test my code",
                                  "I use a source code version control system e.g. Git",
                                  "I use open source software when programming",
                                  "I write code to automatically quality assure data",
                                  "I write repetitive elements in my code as functions",
                                  "My team applies the principles set out in the Aqua book when carrying out analysis as code",
                                  "My team open sources its code", each = 6)),
```

Comment (RuSnook) [reply tests/testthat/test-summarise_coding_practices.R:36]: Can do it this way instead so it matches the format below. I would guess that it would have a slight performance benefit if you were using in a more labour intensive context, although that's not really relevant here. but just adding in case you weren't aware of this way.

File: tests/testthat/test-summarise_language_status.R [hunk 2]
```diff
@@ -26,59 +26,45 @@ dummy_data <- data.frame(
...
-  "SPSS",
-  "SQL",
-  "Stata",
-  "VBA"
-)
-
 dummy_data <- derive_language_status(dummy_data)
 
-dummy_output <- summarise_language_status(dummy_data)
+test_that("summarise_language_status missing data is handled correctly", {
```
Comment (RuSnook) [inline tests/testthat/test-summarise_language_status.R:31]: Can't see where missing data is in the input. Should there be some for this test?

File: tests/testthat/test-summarise_rap_advanced.R [hunk 3]
```diff
@@ -1,29 +1,23 @@
+
 dummy_data <- data.frame(code_freq = c("Never", rep("Sometimes", 4), rep("regularly", 2), rep("All the time", 6)),
                          advanced_rap_score = c(0, 1, 2, 2, 3, 3, 3, 4, 4, 5, 6, 7, 7))
 
-dummy_output <- summarise_rap_advanced(dummy_data)
+test_that("summarise_rap_advanced missing data is handled correctly", {
```
Comment (RuSnook) [inline tests/testthat/test-summarise_rap_advanced.R:5]: Should there be missing data in the input for this test?

File: tests/testthat/test-summarise_rap_basic.R [hunk 4]
```diff
@@ -1,29 +1,23 @@
+
 dummy_data <- data.frame(code_freq = c("Never", rep("Sometimes", 4), rep("All the time", 6)),
                          basic_rap_score = c(0, 1, 2, 2, 3, 3, 3, 4, 4, 5, 6))
 
-dummy_output <- summarise_rap_basic(dummy_data)
+test_that("summarise_rap_basic missing data is handled correctly", {
```
Comment (RuSnook) [inline tests/testthat/test-summarise_rap_basic.R:5]: Should there be missing data in the input for this test?

File: tests/testthat/test-summarise_rap_knowledge.R [hunk 5]
```diff
@@ -1,32 +1,40 @@
...
-test_that("Validation checks work", {
+
+dummy_data <- data.frame(heard_of_RAP = c("No", rep("Yes", 13)),
+                         know_RAP_champ = c(rep("I don't know what a RAP champion is", 2),
+                                            rep("I know what a RAP champion is but don't know who the RAP champion in my department is", 3),
+                                            rep("I know what a RAP champion is and there is no RAP champion in my department", 4),
+                                            rep("I know who the RAP champion in my department is", 5))
+)
+
+test_that("summarise_rap_knowledge missing data is handled correctly", {
```
Comment (RuSnook) [inline tests/testthat/test-summarise_rap_knowledge.R:9]: Should there be missing data in the input for this test?

**Comment by ldavies99** [comment]
test-derive_basic_rap_scores needs to be fixed

**Review by RuSnook — APPROVED** [review]
Looks all good to me now.
